trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  resourceGroup: 'rg-eastus-demo'
  location: 'eastus'
  storageAccount: 'storageacctdemo1234'  # must be lowercase and globally unique

steps:
  - task: AzureCLI@2
    displayName: 'Create RG and Storage Account'
    inputs:
      azureSubscription: 'AzureServiceConnection'  # Replace with your actual service connection name
      scriptType: 'bash'
      scriptLocation: 'inlineScript'
      inlineScript: |
        echo "Creating Resource Group..."
        az group create --name ${{ variables.resourceGroup }} --location ${{ variables.location }}

        echo "Creating Storage Account..."
        az storage account create \
          --name ${{ variables.storageAccount }} \
          --resource-group ${{ variables.resourceGroup }} \
          --location ${{ variables.location }} \
          --sku Standard_LRS \
          --kind StorageV2 \
          --enable-hierarchical-namespace false
      workingDirectory: $(System.DefaultWorkingDirectory)
